name = "Comparator"
version = "0.1.0"
defaultTargets = ["comparator", "query_decls"]

[[lean_lib]]
name = "Comparator"

[[lean_exe]]
name = "comparator"
root = "Main"

[[lean_exe]]
name = "query_decls"
root = "scripts.QueryDecls"

[[require]]
scope = "leanprover"
name = "Lean4Checker"
rev = "66e11cea12f5ba215d76b15b7f8495141bf52c6c"

[[require]]
scope = "leanprover"
name = "lean4export"
rev = "v4.28.0"
