name = "Comparator"
version = "0.1.0"
defaultTargets = ["comparator", "query_decls"]

[[lean_lib]]
name = "Comparator"

[[lean_exe]]
name = "comparator"
root = "Main"

[[lean_exe]]
name = "query_decls"
root = "scripts.QueryDecls"

[[require]]
scope = "leanprover"
name = "lean4export"
rev = "v4.33.0"
